
language: python
python:
    - "2.7"
# command to install dependencies
install:
# command to run tests (switch to pipenv instead of requirements.txt)
    - 'pip install pipenv'
    - 'pipenv install --dev'
    - 'pip install --upgrade setuptools'
    - 'pyinstaller table_describer/tbl_desc.py --onedir'
    - 'python zipdist.py'
#   - 'pipenv shell'
script: pytest

deploy:
  provider: releases
  api_key: $github_secret_personal_access_token
  file: 'table_describer/tbl_desc.zip'
  skip_cleanup: true
  on:
    tags: true # only deploy on tagged build
    #repo: ryansutc/table_describer